name: DevOps Library project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  start-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install dependencies
      run: |
        npm install
        npx playwright install
    - name: Run Server
      run: |
        cd server
        npm run server &
        cd ../
    - name: Start frontend
      run: npm run start &
    - name: Test
      run: npm run test
    
  deploy:
    runs-on: ubuntu-latest
    needs: start-and-test
    steps:
      - name: checkout repository
        run: actions/checkout@v4
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.API_KEY }}
          wait-for-success: true
    
      
      
